#ifndef APPLICATION_USER_PHYSICALINTERFACE_BUTTONS_H_
#define APPLICATION_USER_PHYSICALINTERFACE_BUTTONS_H_


enum buttons{IDLE, BUTTON_1};


#endif /* APPLICATION_USER_PHYSICALINTERFACE_BUTTONS_H_ */
